:green_heart: Improve Tailscale connection and deployment checks with timeout handling

diff --git a/.github/workflows/deploy-production.yml b/.github/workflows/deploy-production.yml
--- a/.github/workflows/deploy-production.yml
+++ b/.github/workflows/deploy-production.yml
@@ -40,13 +40,18 @@ jobs:
       - name: Check connection
         shell: bash
         run: |
+          echo "[INFO]: Checking Tailscale connection..."
           count=30
           while ! ping -c 1 ${{ secrets.TS_HOST }} ; do
+            if [ ${count} -le 0 ]; then
+              echo "[ERROR]: Timed out waiting for Tailscale host!"
+              exit 1
+            fi
             echo "Waiting to ping...";
             sleep 1;
-            let count=count-1
+            ((count--))
           done
-          echo "OK: Connection established!"
+          echo "[OK]: Connection established!"
       - name: Run pre-deployment script
         run: sleep 3 && ssh SERVER 'cd ${{ secrets.DEPLOY_PROJECT_DIR }} && ./scripts/pre-deploy.sh'
       - name: Backup
@@ -61,12 +66,17 @@ jobs:
       - name: Test deployment
         shell: bash
         run: |
+          echo "[INFO]: Checking deployment..."
           count=120
           while ! curl -kIf ${{ secrets.PUBLIC_URL }} ; do
+            if [ ${count} -le 0 ]; then
+              echo "[ERROR]: Timed out waiting for deployment!"
+              exit 1
+            fi
             echo "Waiting to curl...";
             sleep 1;
-            let count=count-1
+            ((count--))
           done
-          echo "OK: Deployment successful!"
+          echo "[OK]: Deployment successful!"
       - name: Run post-deployment script
         run: ssh SERVER 'cd ${{ secrets.DEPLOY_PROJECT_DIR }} && ./scripts/post-deploy.sh'
